source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZSilkKit_Example', :exclusive => true do
  pod "DZSilkKit", :path => "../"
end

target 'DZSilkKit_Tests', :exclusive => true do
  pod "DZSilkKit", :path => "../"

  pod 'FBSnapshotTestCase'
end
